<h1 style="text-align: center;">NumPy Fundamentals</h1>

### Contents

- [Getting Started with NumPy](https://numpy.org/)
- [Installing NumPy](#Installing-NumPy)
- [Importing NumPy](#Importing-NumPy)
- [Initializing Arrays in NumPy](#Initializing-Arrays-in-NumPy)
- [Understanding Array Attributes](#Understanding-Array-Attributes)
- [Data Types in NumPy Arrays](#Data-Types-in-NumPy-Arrays)
- [Operations on NumPy Arrays](#Operations-on-NumPy-Arrays)
- [Array Functions in NumPy](#Array-Functions-in-NumPy)
- [Indexing & Slicing in Arrays](#Indexing-&-Slicing-in-Arrays)
- [Iterating through Arrays](#Iterating-through-Arrays)
- [Reshaping NumPy Arrays](#Reshaping-NumPy-Arrays)
- [Stacking & Splitting Arrays](#Stacking-&-Splitting-Arrays)

### Installing NumPy

In [1]:
# !pip install numpy

### Importing NumPy

In [2]:
import numpy as np

### Initializing Arrays in NumPy

In [3]:
# 1 Dimensional or Vector
arr = np.array([1, 2, 3])

print(f"Type: {type(arr)}\nArray: {arr}")

Type: <class 'numpy.ndarray'>
Array: [1 2 3]


In [4]:
# 2 Dimensional or Matrix
arr = np.array(
    [
        [1, 2, 3],
        [4, 5, 6],
    ]
)

print(arr)

[[1 2 3]
 [4 5 6]]


In [5]:
# 3 Dimensional or Tensor
arr = np.array(
    [
        [[1, 2], [3, 4]],
        [[5, 6], [7, 8]],
    ]
)

print(arr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [6]:
# specify the data type as float
np.array([1, 2, 3], dtype=float)

array([1., 2., 3.])

In [8]:
# specify the data type as bool
np.array([0, 2, 3], dtype=bool)

array([False,  True,  True])

In [8]:
# specify the data type as complex
np.array([1, 2, 3], dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [10]:
# reshape changes the dimensions of a array
arr = np.arange(1, 21, 2)      # arange and range are same

arr.reshape(2, 5)

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19]])

In [10]:
# converting linear to 4 dimensional array
arr = np.arange(16)
arr.reshape(2, 2, 2, 2)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [11]:
# generating NumPy arrays filled with ones
arr1 = np.ones((1, ))
arr2 = np.ones((3, 2))

print(f"Array 01: {arr1}")
print(f"Array 02: \n{arr2}")

Array 01: [1.]
Array 02: 
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [12]:
# generating NumPy arrays filled with zeros
arr1 = np.zeros((1, ))
arr2 = np.zeros((3, 2))

print(f"Array 01: {arr1}")
print(f"Array 02: \n{arr2}")

Array 01: [0.]
Array 02: 
[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [13]:
# generating NumPy arrays filled with random values
arr1 = np.random.random((1, ))
arr2 = np.random.random((3, 2))

print(f"Random Array 01: {arr1}")
print(f"Random Array 02: \n{arr2}")

Random Array 01: [0.58171684]
Random Array 02: 
[[0.24047679 0.20455786]
 [0.74359467 0.48220214]
 [0.13158371 0.637919  ]]


In [14]:
# linear space
# np.linspace(lower_range, upper_range, size)
np.linspace(-10, 10, 5)

array([-10.,  -5.,   0.,   5.,  10.])

In [15]:
# generating the identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Understanding Array Attributes

In [16]:
arr1 = np.arange(10)
arr2 = np.arange(12, dtype=float).reshape(3, 4)
arr3 = np.arange(8).reshape(2, 2, 2)

print(f"Array 01: {arr1}")
print(f"\nArray 02:\n{arr2}")
print(f"\nArray 03:\n{arr3}")

Array 01: [0 1 2 3 4 5 6 7 8 9]

Array 02:
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]

Array 03:
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [17]:
# checking the dimensions of an array

print(f"Dimension of 1st Array: {arr1.ndim}")
print(f"Dimension of 2nd Array: {arr2.ndim}")
print(f"Dimension of 3rd Array: {arr3.ndim}")

Dimension of 1st Array: 1
Dimension of 2nd Array: 2
Dimension of 3rd Array: 3


In [18]:
# checking the shape of an array
# for 3D (num_of_2D, rows, cols)

print(f"Shape of 1st Array: {arr1.shape}")
print(f"Shape of 2nd Array: {arr2.shape}")
print(f"Shape of 3rd Array: {arr3.shape}")

Shape of 1st Array: (10,)
Shape of 2nd Array: (3, 4)
Shape of 3rd Array: (2, 2, 2)


In [19]:
# checking the size of an array

print(f"Size of 1st Array: {arr1.size}")
print(f"Size of 2nd Array: {arr2.size}")
print(f"Size of 3rd Array: {arr3.size}")

Size of 1st Array: 10
Size of 2nd Array: 12
Size of 3rd Array: 8


In [20]:
# checking the item size in memory (bytes)

print(f"Item Size of 1st Array: {arr1.itemsize} bytes per item")
print(f"Item Size of 2nd Array: {arr2.itemsize} bytes per item")
print(f"Item Size of 3rd Array: {arr3.itemsize} bytes per item")

Item Size of 1st Array: 4 bytes per item
Item Size of 2nd Array: 8 bytes per item
Item Size of 3rd Array: 4 bytes per item


In [21]:
# checking the total memory occupied by an array

print(f"Total Memory occupied by 1st Array: {arr1.nbytes} bytes")
print(f"Total Memory occupied by 2nd Array: {arr2.nbytes} bytes")
print(f"Total Memory occupied by 3rd Array: {arr3.nbytes} bytes")

Total Memory occupied by 1st Array: 40 bytes
Total Memory occupied by 2nd Array: 96 bytes
Total Memory occupied by 3rd Array: 32 bytes


### Data Types in NumPy Arrays

In [22]:
# checking the data type of an array

print(f"Data Type of 1st Array: {arr1.dtype}")
print(f"Data Type of 2nd Array: {arr2.dtype}")
print(f"Data Type of 3rd Array: {arr3.dtype}")

Data Type of 1st Array: int32
Data Type of 2nd Array: float64
Data Type of 3rd Array: int32


In [23]:
# changing the data types of an array
# data type of arr1 changes from int32 to int64
x1 = arr1.astype(np.int64)
# data type of arr2 changes from float64 to float32
x2 = arr2.astype(np.float32)
# data type of arr3 changes from int32 to float64
x3 = arr3.astype(np.float64)
# data type of arr1 changes from int32 to bool
x4 = arr1.astype(bool)
# data type of arr1 changes from int32 to complex
x5 = arr1.astype(complex)

print(f"Data Type of 1st Array: {x1.dtype}")
print(f"Data Type of 2nd Array: {x2.dtype}")
print(f"Data Type of 3rd Array: {x3.dtype}")
print(f"Data Type of 4th Array: {x4.dtype}")
print(f"Data Type of 5th Array: {x5.dtype}")

Data Type of 1st Array: int64
Data Type of 2nd Array: float32
Data Type of 3rd Array: float64
Data Type of 4th Array: bool
Data Type of 5th Array: complex128


In [24]:
print(f"Array 01: {x1}")
print(f"Array 04: {x4}")
print(f"Array 05: {x5}")

Array 01: [0 1 2 3 4 5 6 7 8 9]
Array 04: [False  True  True  True  True  True  True  True  True  True]
Array 05: [0.+0.j 1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j 6.+0.j 7.+0.j 8.+0.j 9.+0.j]


### Operations on NumPy Arrays

In [12]:
arr1 = np.arange(12).reshape(3, 4)
arr2 = np.arange(12, 24).reshape(3, 4)

print(f"Array 01:\n{arr1}")
print(f"\nArray 02:\n{arr2}")

Array 01:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Array 02:
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [26]:
# arithmetic operations
print(f"Array:\n{arr1}")
print(f"\nAdditon:\n{arr1+2}")
print(f"\nSubtraction:\n{arr1-2}")
print(f"\nMultiplication:\n{arr1*2}")
print(f"\nDivision:\n{arr1/2}")
print(f"\nPower:\n{arr1**2}")

Array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Additon:
[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]

Subtraction:
[[-2 -1  0  1]
 [ 2  3  4  5]
 [ 6  7  8  9]]

Multiplication:
[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]

Division:
[[0.  0.5 1.  1.5]
 [2.  2.5 3.  3.5]
 [4.  4.5 5.  5.5]]

Power:
[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]


In [15]:
# relational operations: >, <, >=, <=, == !=
print(arr1 >= 5)
arr1[arr1 >= 10]


[[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]


array([10, 11])

In [28]:
# vector operations

print(f"Addition:\n{arr1+arr2}")
print(f"\nMultiplication:\n{arr1*arr2}")
print(f"\nComparison:\n{arr1<arr2}")

Addition:
[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]

Multiplication:
[[  0  13  28  45]
 [ 64  85 108 133]
 [160 189 220 253]]

Comparsion:
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


### Array Functions in NumPy

In [18]:
arr1 = np.random.random((3, 3))
arr1 = np.round(arr1*100)

print(f"Array 01:\n{arr1}")

Array 01:
[[33. 31. 79.]
 [88. 91. 57.]
 [50. 16. 64.]]


In [30]:
# max/min/sum/prod
print(f"Max: {np.max(arr1)}")
print(f"Min: {np.min(arr1)}")
print(f"Sum: {np.sum(arr1)}")
print(f"Product: {np.prod(arr1)}")

Max: 64.0
Min: 5.0
Sum: 373.0
Product: 62563924416000.0


In [31]:
# operation on each row, axis=1, columns will be index and operation applied on rows
# operation on each col, axis=0

print(f"Max per Row: {np.max(arr1, axis=1)}")
print(f"Max per Col: {np.max(arr1, axis=0)}")

Max per Row: [64. 58. 50.]
Max per Col: [64. 58. 49.]


In [32]:
# statistical functions
print(f"Mean: {np.mean(arr1)}")
print(f"Median: {np.median(arr1)}")
print(f"Variance: {np.var(arr1)}")
print(f"Standard Deviation: {np.std(arr1)}")

Mean: 41.44444444444444
Median: 47.0
Variance: 318.91358024691357
Standard Deviation: 17.858151646990613


In [33]:
print(f"Calculating Mean per Row: {np.mean(arr1, axis=1)}")
print(f"Calculating Mean per Col: {np.mean(arr1, axis=0)}")

Calculating Mean per Row: [51.33333333 40.66666667 32.33333333]
Calculating Mean per Col: [53.66666667 34.66666667 36.        ]


In [34]:
# trigonometric functions

print(f"Cos:\n{np.cos(arr1)}")
print(f"\nSin:\n{np.sin(arr1)}")
print(f"\nTan:\n{np.tan(arr1)}")

Cos:
[[ 0.39185723 -0.98733928  0.30059254]
 [-0.99233547  0.11918014 -0.27516334]
 [ 0.96496603  0.28366219 -0.39998531]]

Sin:
[[ 0.92002604 -0.15862267 -0.95375265]
 [ 0.12357312  0.99287265 -0.96139749]
 [-0.26237485 -0.95892427 -0.91652155]]

Tan:
[[ 2.34786031  0.1606567  -3.17290855]
 [-0.12452757  8.33085685  3.49391565]
 [-0.27190061 -3.38051501  2.29138799]]


In [35]:
# dot product
x1 = np.arange(12).reshape(3, 4)
x2 = np.arange(12, 24).reshape(4, 3)

print(f"Dot Product:\n{np.dot(x1, x2)}")

Dot Product:
[[114 120 126]
 [378 400 422]
 [642 680 718]]


In [36]:
# log and exponent
print(f"Log:\n{np.log(x2)}")
print(f"\nExponent:\n{np.exp(x2)}")

Log:
[[2.48490665 2.56494936 2.63905733]
 [2.7080502  2.77258872 2.83321334]
 [2.89037176 2.94443898 2.99573227]
 [3.04452244 3.09104245 3.13549422]]

Exponent:
[[1.62754791e+05 4.42413392e+05 1.20260428e+06]
 [3.26901737e+06 8.88611052e+06 2.41549528e+07]
 [6.56599691e+07 1.78482301e+08 4.85165195e+08]
 [1.31881573e+09 3.58491285e+09 9.74480345e+09]]


In [37]:
arr = np.random.random((2, 3))*100

print(f"Array:\n{arr}")
print(f"\nRound:\n{np.round(arr)}")
print(f"\nFloor:\n{np.floor(arr)}")
print(f"\nCeil:\n{np.ceil(arr)}")

Array:
[[94.45172454 33.92483145 26.31946118]
 [81.79124133 87.96341085 49.98209588]]

Round:
[[94. 34. 26.]
 [82. 88. 50.]]

Floor:
[[94. 33. 26.]
 [81. 87. 49.]]

Ceil:
[[95. 34. 27.]
 [82. 88. 50.]]


### Indexing & Slicing in Arrays

In [38]:
arr1 = np.arange(10)
arr2 = np.arange(12).reshape(3, 4)
arr3 = np.arange(8).reshape(2, 2, 2)

In [39]:
print(f"array = {arr1}\n")

print(f"array[0] = {arr1[0]}")
print(f"array[-1] = {arr1[-1]}\n")

print(f"array[1:5] = {arr1[1:5]}")
print(f"array[::2] = {arr1[::2]}\n")

print(f"array[:] = {arr1[:]}")
print(f"array[::-1] = {arr1[::-1]}")

array = [0 1 2 3 4 5 6 7 8 9]

array[0] = 0
array[-1] = 9

array[1:5] = [1 2 3 4]
array[::2] = [0 2 4 6 8]

array[:] = [0 1 2 3 4 5 6 7 8 9]
array[::-1] = [9 8 7 6 5 4 3 2 1 0]


In [40]:
print(f"array =\n{arr2}\n")

print(f"array[2, 1] = {arr2[2, 1]}")
print(f"array[1, 3] = {arr2[1, 3]}\n")

print(f"array[-1, -3] = {arr2[-1, -3]}")
print(f"array[-3, -2] = {arr2[-3, -2]}\n")

print(f"array[0, :] = {arr2[0, :]}")
print(f"array[:, 2] = {arr2[:, 2]}\n")

print(f"array[1, 1:3] = {arr2[1, 1:3]}")
print(f"array[2, 2:4] = {arr2[2, 2:4]}\n")

print(f"array[:2, 1::2] =\n{arr2[:2, 1::2]}\n")
print(f"array[0:2, 1:3] =\n{arr2[0:2, 1:3]}\n")
print(f"array[::2, :] =\n{arr2[::2, :]}\n")
print(f"array[::2, ::3] =\n{arr2[::2, ::3]}\n")
print(f"array[::2, ::2] =\n{arr2[::2, ::2]}\n")

array =
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

array[2, 1] = 9
array[1, 3] = 7

array[-1, -3] = 9
array[-3, -2] = 2

array[0, :] = [0 1 2 3]
array[:, 2] = [ 2  6 10]

array[1, 1:3] = [5 6]
array[2, 2:4] = [10 11]

array[:2, 1::2] =
[[1 3]
 [5 7]]

array[0:2, 1:3] =
[[1 2]
 [5 6]]

array[::2, :] =
[[ 0  1  2  3]
 [ 8  9 10 11]]

array[::2, ::3] =
[[ 0  3]
 [ 8 11]]

array[::2, ::2] =
[[ 0  2]
 [ 8 10]]



In [41]:
print(f"array =\n{arr3}\n")

print(f"array[0, 0, 0] = {arr3[0, 0, 0]}")
print(f"array[1, 0, 1] = {arr3[1, 0, 1]}")
print(f"array[0, 1, 0] = {arr3[0, 1, 0]}\n")

print(f"array[-1, -2, -1] = {arr3[-1, -2, -1]}")
print(f"array[-2, -1, -1] = {arr3[-2, -1, -1]}")

array =
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]

array[0, 0, 0] = 0
array[1, 0, 1] = 5
array[0, 1, 0] = 2

array[-1, -2, -1] = 5
array[-2, -1, -1] = 3


In [42]:
arr3 = np.arange(27).reshape(3, 3, 3)
print(f"array =\n{arr3}\n")

print(f"array[1] =\n{arr3[1]}\n")
print(f"array[::2] =\n{arr3[::2]}\n")
print(f"array[:, 1] =\n{arr3[:, 1]}\n")

print(f"array[0, 1, :] = {arr3[0, 1, :]}")
print(f"array[:, 1, 1] = {arr3[:, 1, 1]}")
print(f"array[0, :, 1] = {arr3[0, :, 1]}\n")

array =
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]

array[1] =
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]

array[::2] =
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]

array[:, 1] =
[[ 3  4  5]
 [12 13 14]
 [21 22 23]]

array[0, 1, :] = [3 4 5]
array[:, 1, 1] = [ 4 13 22]
array[0, :, 1] = [1 4 7]



In [43]:
print(f"array[2, 1:, 1:] =\n{arr3[2, 1:, 1:]}\n")
print(f"array[:, 1:, 1:] =\n{arr3[:, 1:, 1:]}\n")
print(f"array[::2, 0, ::2] =\n{arr3[::2, 0, ::2]}")

array[2, 1:, 1:] =
[[22 23]
 [25 26]]

array[:, 1:, 1:] =
[[[ 4  5]
  [ 7  8]]

 [[13 14]
  [16 17]]

 [[22 23]
  [25 26]]]

array[::2, 0, ::2] =
[[ 0  2]
 [18 20]]


### Iterating through Arrays

In [44]:
# flexible way to iterate over elements of an array
arr_2d = np.arange(9).reshape(3, 3)

iter_obj = np.nditer(arr_2d)

print(f"2D Array=\n{arr_2d}\n")
print(f"nditer:")
for element in iter_obj:
    print(element, end=" ")

2D Array=
[[0 1 2]
 [3 4 5]
 [6 7 8]]

nditer:
0 1 2 3 4 5 6 7 8 

In [45]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

iter_obj = np.nditer([arr1, arr2])

print("Method 01:")
for element in iter_obj:
    print(element)

iter_obj.reset()

print("\nMethod 02:")
for x, y in iter_obj:
    print(x, y)

Method 01:
(array(1), array(5))
(array(2), array(6))
(array(3), array(7))
(array(4), array(8))

Method 02:
1 5
2 6
3 7
4 8


### Reshaping NumPy Arrays

In [46]:
arr = np.arange(12).reshape(3, 4)

print(f"Array =\n{arr}\n")
# np.transpose and arr.T are same
print(f"Transpose =\n{np.transpose(arr)}\n")
print(f"Ravel = {np.ravel(arr)}")   # flattens the array.

Array =
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Transpose =
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]

Ravel = [ 0  1  2  3  4  5  6  7  8  9 10 11]


### Stacking & Splitting Arrays

In [47]:
arr1 = np.arange(12).reshape(3, 4)
arr2 = np.arange(12, 24).reshape(3, 4)

print(f"Array 01:\n{arr1}\n")
print(f"Array 02:\n{arr2}")

Array 01:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Array 02:
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [48]:
np.hstack((arr1, arr2))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [49]:
np.hstack((arr1, arr2, arr1))

array([[ 0,  1,  2,  3, 12, 13, 14, 15,  0,  1,  2,  3],
       [ 4,  5,  6,  7, 16, 17, 18, 19,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 20, 21, 22, 23,  8,  9, 10, 11]])

In [50]:
np.vstack((arr1, arr2))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [51]:
np.hsplit(arr1, 2)      # it has to be equal division

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [52]:
np.vsplit(arr1, 3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]